name = "Zilindroa"
uuid = "4fc2b7b2-3c57-4a1c-b739-04289ec73312"
authors = ["Diogo Ribeiro"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
